version: '3'
services:
  testcafe:
    image: 'testcafe/testcafe'
    volumes:
      - .:/tests
    #command: 'chromium --no-sandbox,firefox' /tests/test-example.js
    #entrypoint: ["chromium --no-sandbox,firefox", "/tests/test-example.js"]
    entrypoint: ["/opt/testcafe/docker/testcafe-docker.sh", "chromium --no-sandbox,firefox", "/tests/test-example.js"]
